<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatRepository extends EntityRepository
{
}